server:
  port: 9001
spring:
  application:
    name: ly-registry
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka
    fetch-registry: false
    register-with-eureka: false