server:
  port: 9003
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
ly:
  upload:
    allowTypes:
      - image/jpg
      - image/jpeg
      - image/png
      - image/bmp
    baseUrl: http://image.leyou.com/
fdfs:
  connect-timeout: 600
  so-timeout: 2500
  thumb-image:
    height: 60
    width: 60
  tracker-list:
    - 192.168.43.130:22122