server:
  port: 9006
spring:
  application:
    name: sms-service
  rabbitmq:
    virtual-host: /leyou
    username: leyou
    password: leyou
    host: 192.168.43.130
  redis:
    host: 192.168.43.130
ly:
  sms:
    accessKeyId: LTAIjyu7vcsPfjaD # 你自己的accessKeyId
    accessKeySecret: 8TZqjEHC37GkyLDPrLurJTIVp6B0Wt # 你自己的AccessKeySecret
    signName: 十次方 # 签名名称
    verifyCodeTemplate: SMS_167400918 # 模板名称