server:
  port: 9004
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.43.130:9300
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    virtual-host: /leyou
    username: leyou
    password: leyou
    host: 192.168.43.130
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
