server:
  port: 9008
spring:
  application:
    name: leyou-config
  cloud:
    config:
      server:
        git:
          uri: http://192.168.138.100:3000/test/leyou_config.git
          username: test
          password: test
  rabbitmq:
    host: 192.168.138.100
    port: 5672
    username: test
    password: test
    virtual-host: /test
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
