server:
  port: 9008
spring:
  application:
    name: leyou-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zhuzhiqiang997/leyou-config.git
          username: zhuzhiqiang997
          password: zzq123456
  rabbitmq:
    host: 192.168.43.130
    username: leyou
    password: leyou
    virtual-host: /leyou
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh