server:
  port: 8002
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?characterEncoding=UTF-8
    username: test
    password: 123456
  redis:
    host: 192.168.43.130
  rabbitmq:
    username: leyou
    password: leyou
    virtual-host: /leyou
    host: 192.168.43.130
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

mybatis:
  type-aliases-package: com.leyou.user.pojo